### ISSUE TITLE
eval_LFW验证精度问题

### ISSUE THREAD

**Issue by BaseJiang** [bubbliiiing/facenet-pytorch#28]
博主你好，我用的tag2.0的工程使用你提供的训练模型，在执行eval_LFW.py程序的时候，发现精度只有0.78,我看表格里写的是0.98,请问，这是什么原因？
Accuracy: 0.78083+-0.02031
Best_thresholds: 1.20000
Validation rate: 0.10367+-0.01567 @ FAR=0.00100

**Comment by ultreee** [comment]
作者似乎修改了lfw数据集，原lfw数据集大小178M，作者提供的lfw数据集大小31M。
我使用原数据集预测准确率大概七十几，而作者提供的数据集预测准确率可达98。

**Comment by 851942817** [comment]
请问一下Best_thresholds: 1.20000  是什么意思啊？我在进行模型预测的时候，同一个人的人脸计算的距离0.5，不同人脸计算距离0.8左右，但是验证的时候计算给我的Best_thresholds是1.21

**Comment by zxm97** [comment]
> 178M

训练集CASIA是裁剪人脸，178M的LFW人脸没裁剪矫正所以验证精度低，31M的处理过
